res18_pre: 'runs/pre_train/resnet18.pth'
img_train: 'Data/Unseen_aff/Img_train.txt'
img_val: 'Data/Unseen_aff/Img_test.txt'
img_test: 'Data/Unseen_aff/Img_test.txt'
point_train: 'Data/Unseen_aff/Point_train.txt'
point_val: 'Data/Unseen_aff/Point_test.txt'
point_test: 'Data/Unseen_aff/Point_test.txt'
batch_size: 32
lr: 0.0001
Epoch: 50
Setting: 'Unseen_aff'
num_heads: 4
emb_dim: 512
proj_dim: 512
N_p: 64
N_raw: 2048
num_affordance: 24
pairing_num: 2
run_type: 'train'

human_dictionary_train: 'Data/Unseen_aff/hk_train.txt'
human_dictionary_val: 'Data/Unseen_aff/hk_test.txt'
human_dictionary_test: 'Data/Unseen_aff/hk_test.txt'

object_dictionary_train: 'Data/Unseen_aff/ok_train.txt'
object_dictionary_val: 'Data/Unseen_aff/ok_test.txt'
object_dictionary_test: 'Data/Unseen_aff/ok_test.txt'