res18_pre: 'runs/pre_train/resnet18.pth'
img_train: 'Data/Seen/Img_train.txt'
img_val: 'Data/Seen/Img_val.txt'
img_test: 'Data/Seen/Img_test.txt'
point_train: 'Data/Seen/Point_train.txt'
point_val: 'Data/Seen/Point_val.txt'
point_test: 'Data/Seen/Point_test.txt'
batch_size: 16
lr: 0.0001
Epoch: 65
Setting: 'Seen'
num_heads: 4
emb_dim: 512
proj_dim: 512
N_p: 64
N_raw: 2048
num_affordance: 24
pairing_num: 2
run_type: 'train'

human_dictionary_train: 'Data/Seen/hk_train.txt'
human_dictionary_val: 'Data/Seen/hk_val.txt'
human_dictionary_test: 'Data/Seen/hk_test.txt'

object_dictionary_train: 'Data/Seen/ok_train.txt'
object_dictionary_val: 'Data/Seen/ok_val.txt'
object_dictionary_test: 'Data/Seen/ok_test.txt'